set_property SRC_FILE_INFO {cfile:{C:/Users/upsag/Desktop/Chula/ 3-1/HW_Syn_Lab/Final_Project/Final_Project.srcs/constrs_1/imports/HWSYNLAB2021/Basys3_Master.xdc} rfile:../../../Final_Project.srcs/constrs_1/imports/HWSYNLAB2021/Basys3_Master.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W5 [get_ports clk]
set_property src_info {type:XDC file:1 line:267 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B18 [get_ports RsRx]
set_property src_info {type:XDC file:1 line:269 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A18 [get_ports RsTx]
